### ISSUE TITLE
for Anubhav

### ISSUE THREAD

**Issue by NotToxic00** [NotToxic00/statusBot#1]
```py
@commands.is_owner()
    @commands.command()
    async def testDB(self,ctx,*id):
        async with aiosqlite.connect('data/db/Guild.sql') as db:
            cursor1 = await db.execute("SELECT Channel_Id_voice_channels FROM Count WHERE Guild_ID = (?)", (id,))
            name1 = await cursor1.fetchall()
            await ctx.send(name1)
```
when i wont get id from db i get the error 
```py
returning exception Error binding parameter 0 - probably unsupported type.
Traceback (most recent call last):
  File "C:\Users\NotToxic89\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiosqlite\core.py", line 95, in run
    result = function()
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
Ignoring exception in command testDB:
Traceback (most recent call last):
  File "C:\Users\NotToxic89\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "E:\PythonProject\Status+\bot\sys\own.py", line 51, in testDB
    cursor1 = await db.execute("SELECT Channel_Id_voice_channels FROM Count WHERE Guild_ID = (?)", (id,))
  File "C:\Users\NotToxic89\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiosqlite\core.py", line 160, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "C:\Users\NotToxic89\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiosqlite\core.py", line 109, in _execute
    return await future
  File "C:\Users\NotToxic89\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiosqlite\core.py", line 95, in run
    result = function()
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\NotToxic89\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\NotToxic89\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\NotToxic89\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: InterfaceError: Error binding parameter 0 - probably unsupported type.
```

**Comment by Anubhav1603** [comment]
Ok I will look into the issue soon😸

**Comment by mylaff** [comment]
Now when i see a code problem becomes obvious (i hope so at least, haha).
You are passing an unsupported type as a binding and somewhat you do unpack id argument. Try print(id) to make sure its either string or integer. Let me know in DS dm about results.

**Comment by NotToxic00** [comment]
```py
@commands.is_owner()
    @commands.command()
    async def testDB(self,ctx,id):
        async with aiosqlite.connect('data/db/Guild.sql') as db:
            print(id)
            cursor1 = await db.execute("SELECT Channel_Id_voice_channels FROM Count WHERE Guild_ID = (?)", (id,))
            name1 = await cursor1.fetchall()
            await ctx.send(name1)
``` i fix that Thx all
